version: '3.1'

services:
  api:
    build:
      dockerfile: API/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pgdev
      POSTGRES_PASSWORD: pwdev
      POSTGRES_DB: hotel_dev
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data